name: Simone

on: [push]

jobs:
  ğŸ§™â€â™‚ï¸:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        milliseconds: 500
        token: ${{ secrets.GITHUB_TOKEN }}