name: Simone

on: [push]

jobs:
  Wizarding:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ./
      with:
        milliseconds: 500
        token: ${{ secrets.GITHUB_TOKEN }}